CREATE USER IF NOT EXISTS 'spring'@'localhost' IDENTIFIED BY 'spring';

DROP DATABASE IF EXISTS BOOKS;
USE BOOKS;
GRANT ALL PRIVILEGES ON BOOKS.* TO 'spring'@'localhost';
FLUSH PRIVILEGES;

SET GLOBAL time_zone = '+5:00';
