CREATE USER IF NOT EXISTS 'spring'@'localhost' IDENTIFIED BY 'spring';

DROP DATABASE IF EXISTS MVCBOOKS;
CREATE DATABASE MVCBOOKS;
USE MVCBOOKS;
GRANT ALL PRIVILEGES ON MVCBOOKS.* TO 'spring'@'localhost';
FLUSH PRIVILEGES;

SET GLOBAL time_zone = '+5:00';
