CREATE TABLE BOOK (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  CATEGORY_NAME VARCHAR(100),
  ISBN VARCHAR(14),
  TITLE VARCHAR(500),
  PUBLISHER VARCHAR(100),
  PRICE DECIMAL(5,2),
  UNIQUE UQ_BOOK_1 (ISBN, TITLE),
  PRIMARY KEY (ID)
);
