CREATE TABLE CATEGORY (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100),
  PRIMARY KEY (ID)
);

CREATE TABLE BOOK (
  ID INT NOT NULL AUTO_INCREMENT,
  CATEGORY_ID INT(11),
  ISBN VARCHAR(14),
  TITLE VARCHAR(500),
  PRICE DECIMAL(5,2),
  UNIQUE UQ_BOOK_1 (ISBN, TITLE),
  CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(60),
  LAST_NAME VARCHAR(60),
  DESCRIPTION VARCHAR(2000),
  UNIQUE UQ_AUTHOR_1 (FIRST_NAME, LAST_NAME),
  PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR_BOOK (
  AUTHOR_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE CASCADE,
  CONSTRAINT FK_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);
