CREATE USER IF NOT EXISTS 'spring'@'localhost' IDENTIFIED BY 'spring';

DROP DATABASE IF EXISTS MOREBOOKS;
CREATE DATABASE MOREBOOKS;
USE MOREBOOKS;
GRANT ALL PRIVILEGES ON MOREBOOKS.* TO 'spring'@'localhost';
FLUSH PRIVILEGES;

SET GLOBAL time_zone = '+5:00';
